### ISSUE TITLE
step 8: define eventbridge and integrate them with lambda functions

### ISSUE THREAD

**Issue by warishasan** [panacloud-modern-global-apps/full-stack-serverless-cdk#8]

**Comment by uzairbangee** [comment]
Are you sending the events to the default event bus?

**Comment by Translucent504** [comment]
yes

**Comment by Translucent504** [comment]
you can define a custom event bus with one line of code and then reference that in the lambda by its name. It's unnecessary to provision custom busses for simple use cases. I can add an extra step for creating a custom bus if you want.

>Each event bus in your account can have up to 100 EventBridge rules associated with it, so if your account has many rules, you might want to create custom event buses to associate with some of the rules for your custom application events. Another reason to create custom event buses is to apply different permissions to different event buses. When you set permissions on an event bus, you can specify which other accounts or entire organizations can send events to the event bus.

[Source: AWS DOCS](https://docs.aws.amazon.com/eventbridge/latest/userguide/create-event-bus.html)

**Comment by uzairbangee** [comment]
It's better to add an event bus because it will show the concept of how to create an event bus.
